Add `HTMLDocument.currentScript` and `HTMLElement.getAttribute`.
purescript-web/purescript-web-html pull request #4
Opened 2018-09-12 04:02 UTC by cprussin

Add bindings to [Document.currentScript](https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript) and [Element.getAttribute()](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttribute).

Note that in an attempt to properly implement the note mentioned [here](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttribute) regarding different DOM implementation handling for non existent attributes, the FFI code in this PR has slightly more logic than the trivial implementation.  I don't know how you typically handle cases like this--if you care to target all DOM implementations, I think this is the right thing to do.  If you only care to target later implementations, or if you think consumers should handle this check in purescript code, then I can make it trivial and maybe export a binding to `hasAttribute` as well?  Let me know what you'd prefer here if you'd like modifications and I'm happy to oblige.

2018-09-20 19:25 UTC, cprussin commented
Friendly nudge @garyb .  Any chance of getting it merged and released?  Thanks!

2018-09-20 22:13 UTC, garyb requested changes
`getAttribute` should be defined for `Element` in `purescript-web-dom` rather than `HTMLElement` in here, but this looks good otherwise!

2018-09-21 15:20 UTC, cprussin commented
@garyb removed, thanks.  Didn't realize that it already existed elsewhere :)

2018-09-21 15:22 UTC, cprussin commented
FWIW is there any clear guideline on what goes in `purescript-web-dom` vs `purescript-web-html`?  Seems like the border is a bit blurry to me.

2018-09-21 15:25 UTC, garyb commented
- `-web-dom` implements https://www.w3.org/TR/dom/
- `-web-html` implements https://www.w3.org/TR/html5/

So the border for what belongs where is definitely clear, but as to why what belongs where, it's definitely pretty arbitrary seeming :smile:

2018-09-21 15:26 UTC, merged

2018-09-21 15:26 UTC, cprussin commented
Oh, that's pretty clear :laughing: .  Thanks!

2018-09-21 15:28 UTC, garyb commented
I think the main distinction is the types/interfaces in the `DOM` spec also apply to things like `SVG` documents.